# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Starts Section
  description: Starts Section
  icon: "cottage"

# Defines the structure of this component, as well as the default values
blueprint:
  status: true
  background_image: /images/hero-bg.png
  background_color: '#fcc5c0'
  image: /images/service-image.jpg
  image_alt : ''
  title: 'Services'

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  status:
    label: Active Section
    type: toggle
  background_image:
    label: Background Image
    type: image
  background_color:
    label: Background Color
    type: color
  image:
    label: Section Image
    type: image
  image_alt:
    label: Section Image Alt Text
    type: text
  title:
    label: Section Title
    type: markdown

