# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Starts Section
  description: Starts Section
  icon: "cottage"

# Defines the structure of this component, as well as the default values
blueprint:
  status: true
  background_color: '#C4C4C4'
  background_image: /images/review_bg.png
  image_double_heart: /images/hero-love.png
  image_leaf: /images/leaf-3.png
  list_review:
      - image_acount: /images/service.jpg
        username: 'John Doe'
        position: 'CEO'
        desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo'

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  status:
    label: Active Section
    type: toggle
  background_color:
    label: Background Color
    type: color
  background_image:
    label: Background Image
    type: image
  image_double_heart:
    label: Double Heart Image
    type: image
  image_leaf:
    label: Leaf Image
    type: image
  list_review[*].image_acount:
    label: User Image
    type: image
  list_review[*].username:
    label: Username
    type: text
  list_review[*].position:
    label: Position
    type: text
  list_review[*].desc:
    label: Review Content
    type: markdown
