# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Starts Section
  description: Starts Section
  icon: "cottage"

# Defines the structure of this component, as well as the default values
blueprint:
  status: true
  title_lashTint: 'Lash RefillsLash Lifts & Tints'
  image: /images/brow-tint.png
  desc: 'A lash L will dye and darken your natural lashes to create a balanced, effortless look.<br> A lash lift, or lash perm, will curl and set your natural lashes with a special perming solution and roller.'                  
  desc2: 'We use safe, high-quality, award-winning materials to enhance your natural beauty.'
  desc_link: 'Click here to view our work..'
  link: 'https://www.youtube.com/shorts/-62EiN8nscE'
  service: 'Serivce'
  regular: 'Time'
  member: 'Price'
  list_item:
     -   title: 'Lash Tint'
         price: '15 minutes'
         member: '$40'

 

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  status:
    label: Active Section
    type: toggle
  title_lashTint:
    label: Lash Tint & Lift Title
    type: markdown
  image:
    label: Lash Tint Image
    type: image
  desc_lashTint:
    label: Lash Tint & Lift Description
    type: markdown
  desc2_lashTint:
    label: Additional Description
    type: markdown
  desc_link:
    label: Description Link Text
    type: markdown
  link:
    label: Video Link
    type: text
  service:
    label: Service Title
    type: markdown
  regular:
    label: Time Title
    type: markdown
  member:
    label: Price Title
    type: markdown
  list_item[*].title:
    label: Service Name
    type: markdown
  list_item[*].price:
    label: Service Time
    type: text
  list_item[*].member:
    label: Service Price
    type: text
  