# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: HairService Section
  description: HairService Section
  icon: "cottage"

# Defines the structure of this component, as well as the default values
blueprint:
  status: true
  background_color: '#ffffff'
  title: 'Facial Hair Removal'
  service: 'WAXING - FACE'
  regular: 'REGULAR'
  member: 'Membership'
  list_item:
    -   title: 'Brows/Tint'
        price: '$20'
        member: '$15'

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  status:
    label: Active Section
    type: toggle
  label: Background Color
  type: color
  title:
    label: Section Title
    type: markdown
  service:
    label: Service Type
    type: text
  regular:
    label: Regular Price Label
    type: markdown
  member:
    label: Membership Price Label
    type: markdown
  list_item[*].title:
    label: Service Name
    type: markdown
  list_item[*].price:
    label: Regular Price
    type: text
  list_item[*].member:
    label: Membership Price
    type: text
