# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Lashextension Section
  description: Lashextension Section
  icon: "cottage"

# Defines the structure of this component, as well as the default values
blueprint:
  status: true
  background_color: '#ffffff'
  style: 'Half'
  title: 'Lash Extensions'
  image_caret_right: /images/caret-right1-solid.svg
  image_caret_down: /images/caret-down-solid.svg
  description: 'We include a free consultation on style, curve, length, and design to help you choose between our six different lash extension styles. Our lashes are made of safe, high-quality, and cruelty-free materials.'
  list_service:
     -  title: 'Lash Refills'
        list_item:
          -   title: 'Classic'
              desc: "<p>One extension is glued to one natural lash with 60-70% coverage.</p>"
              desc1: "<p>Artist 1: $225<br>Artist 2: $250<br>Artist 3: $275</p>"
        
# Overrides any fields in the blueprint when viewing this component in the component browser

preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint

_inputs:
  status:
    label: Active Section
    type: toggle
  background_color:
    label: Background Color
    type: color
  style:
    label: Display Style
    type: select
    options:
      - Half
      - Full
  title:
    label: Title Text Section
    type:  markdown
  image_caret_right:
    label: Caret Right Image
    type: image
  image_caret_down:
    label: Caret Down Image
    type: image
  description:
    label: Description Section
    type: markdown
    list_item[*].title:
        label: Title text
        type: markdown
    list_item[*].list_item[*].title:
        label: Title text
        type: text
    list_item[*].list_item[*].desc:
        label: Title text
        type: text
    list_item[*].list_item[*].desc1:
        label: Title text
        type: text
  