# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Starts Section
  description: Starts Section
  icon: "cottage"

# Defines the structure of this component, as well as the default values
blueprint:
  status: true
  list_item:
     -   title: 'Classic'
         image: /images/eye-classic.png
         desc: 'Elevate your natural lashes with the original lash extension technique.'
  image_dot1: /images/dots-large1.png
  image_dot1_alt: 'hero-dots-2'
  image_dot2: /images/dots-large2.png
  image_dot2_alt: 'hero-dots-2'

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
