# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: TreatmentEye Section
  description: TreatmentEye Section
  icon: "cottage"

# Defines the structure of this component, as well as the default values
blueprint:
  status: true
  background_color: '#ffffff'

  list_item:
     -   title: 'Classic'
         image: /images/eye-classic.png
         desc: 'Elevate your natural lashes with the original lash extension technique.'
  image_dot1: /images/dots-large1.png
  image_dot1_alt: 'hero-dots-2'
# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  status:
    label: Active Section
    type: toggle
  label: Background Color
  type: color
  list_item[*].title:
    label: Title 
    type: markdown
  list_item[*].image:
    label: Image 
    type: image
  list_item[*].desc:
    label: Description 
    type: markdown
  image_dot1:
    label: Decorative Image 1
    type: image
  image_dot1_alt:
    label: Decorative Image 1 Alt Text
    type: text