# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Treatment Section
  description: Treatment Section
  icon: "cottage"

# Defines the structure of this component, as well as the default values
blueprint:
    status: true
    background_color: '#ffffff'
    list_treatment:
      - title: 'Classic Lashes'
        desc: 'Classic lashes are a type of eyelash extensions where one individual lash extension is glued onto one natural lash. This creates a natural, enhanced look by adding length and thickness to the lashes.'
        image: /images/hero-face.jpg
        image_alt: ''



# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  status:
    label: Active Section
    type: toggle
  background_color:
    label: Background Color Section
    type: color
  list_treatment[*].title:
    label: Title Section
    type: markdown
  list_treatment[*].desc:
    label: Desc Section
    type: markdown
  list_treatment[*].image:
    label: Image Section
    type: image
  list_treatment[*].image_alt:
    label: Image Alt
    type: text
