# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Hero Contact
  description: Hero Contact
  icon: "cottage"

# Defines the structure of this component, as well as the default values
blueprint:
  status: true
  title: 'Contact Us'
  color: '#FCC5C0'
  heading: 'Get In Touch <br>  With Us'
  background_color: '#ffffff'
  desc: 'Experience Exceptional Beauty Services: Lavilash & Brow is Your Destination!'
  list_item:
  -   image: /images/user-clock-solid.png
      label: 'Mon-Sat: 10:00 AM – 8:00 PM'
      link: '#'

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  status:
    label: Active Section
    type: toggle
  title:
    label: Section Title
    type: markdown
  color:
    label: Section Color
    type: color
  heading:
    label: Section Heading
    type: markdown
 
  desc:
    label: Description
    type: markdown
  list_item[*].image:
    label: Item Image
    type: image
  list_item[*].label:
    label: Item Label
    type: markdown
  list_item[*].link:
    label: Item Link
    type: text
