# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Hero Contact
  description: Hero Contact
  icon: "cottage"

# Defines the structure of this component, as well as the default values
blueprint:
  status: true
  title: 'Contact Us'
  color: '#FCC5C0'
  heading: 'Get In Touch <br>  With Us'
  background_color: '#ffffff'
  desc: 'Experience Exceptional Beauty Services: Lavilash & Brow is Your Destination!'
  list_item:
  -   image: /images/user-clock-solid.png
      label: 'Mon-Sat: 10:00 AM – 8:00 PM'
      link: '#'
  form_width: 1/2
  border: 0
  color_text: "#666666"
  form:
      - fields: text
        status_error: true
        error: Please this is a required field.
        label: Name
        placehoder: Please enter first name
        width_fields: 1/2

     
        
      - fields: email
        status_error: true
        error: Please this is a required field.
        label: Email
        placehoder: Please enter email
        width_fields: 1/2

      
      - fields: tel
        status_error: true
        error: Please this is a required field.
        label: Phone 
        placehoder: Please enter phone number
        width_fields: 1/2

      - fields: text
        status_error: true
        error: Please this is a required field.
        label: Subject
        placehoder: Please enter last name
        width_fields: 1/2  

      - fields: textarea
        status_error: true
        error: Please this is a required field.
        label: Message
        placehoder: Please enter message
        width_fields: full  

      - fields: file
        status_error: true
        error: Please this is a required field.
        label: Attachments 2 (for Resume, References, etc)
        placehoder: PNG, JPG or PDF, smaller than 15MB dasds
        width_fields: full
    
  button:
        background: "#FCC5C0"
        color: "#ffffff"
        border: 25
        text_button: Submit
        variant: solid
        width_button: auto
        align_button: left
        image: images/paper-plane-solid.png
# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  status:
    label: Active Section
    type: toggle
  title:
    label: Title Section
    type: markdown
  color:
    label: Color Title
    type: color
  heading:
    label: Section Heading
    type: markdown
  desc:
    label: Description
    type: markdown
  list_item[*].image:
    label: Item Image
    type: image
  list_item[*].label:
    label: Item Label
    type: text
  list_item[*].link:
    label: Item Link
    type: text
  color_text: 
    label: Color Text 
    type: color
  border:
    label: Border Radius Fields
    type: text
  form_width:
    label: Width Form
    type: select
    options:
      - full
      - 1/2
  form:
    label: Form Contact
    description: Add new form fields.
  form[*].fields:
    label: Type Fields
    type: select
    description:
    options:
      - text
      - textarea
      - email
      - tel
      - file
  form[*].error:
    label: Text Required
    type: text
  form[*].status_error:
    label: Required
    type: toggle
  form[*].label:
    label: Label
    type: text
  form[*].placehoder:
    label: Placehoder
    type: text
  form[*].width_fields:
    label: Width Fields
    type: select
    options:
      - full
      - 1/2
  button.text_button:
    label: Button Text
    type: text
  button.background:
    label: Background Color
    type: color
  button.color:
    label: Text Color
    type: color
  button.border:
    label: Border Radius
    type: text
  button.variant:
    label: Variant Button
    type: select
    options:
      - solid
      - outline
  button.width_button:
    label: Width Button
    type: select
    options:
      - auto
      - 1/2
      - 1/3
      - 1/4
      - full
    
  button.align_button:
    label: Align Button
    type: select
    options:
      - left
      - right
      - center